[package]
name = "graph-memory-demo"
version = "2.0.0"
edition = "2021"

[dependencies]
agent-mem-core = { path = "../../crates/agent-mem-core" }
agent-mem-compat = { path = "../../crates/agent-mem-compat" }
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
anyhow = "1.0"
uuid = "1.0"
chrono = { version = "0.4", features = ["serde"] }
colored = "2.0"
indicatif = "0.17"

[[bin]]
name = "graph-memory-demo"
path = "src/main.rs"
