[package]
name = "storage-migration-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
agent-mem-utils = { path = "../../crates/agent-mem-utils" }
agent-mem-storage = { path = "../../crates/agent-mem-storage" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
