#!/bin/bash
echo "=== AgentMem 代码库分析 ===" 
echo ""
echo "1. 代码规模:"
find crates -name "*.rs" | wc -l | xargs echo "  Rust文件数:"
find crates -name "*.rs" -exec cat {} \; | wc -l | xargs echo "  代码总行数:"
echo ""
echo "2. Crate结构:"
find crates -name "Cargo.toml" | wc -l | xargs echo "  Crate数量:"
echo ""
echo "3. TODO统计:"
grep -r "TODO\|FIXME" crates --include="*.rs" | wc -l | xargs echo "  TODO总数:"
echo ""
echo "4. Mock代码:"
grep -r "mock" crates --include="*.rs" -i | grep -v test | wc -l | xargs echo "  Mock相关:"
echo ""
echo "5. 未实现函数:"
grep -r "unimplemented!\|todo!" crates --include="*.rs" | wc -l | xargs echo "  未实现:"
