[package]
name = "personalization-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-mem-compat = { path = "../../crates/agent-mem-compat" }
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
