/* AgentDB Core C API */
/* Auto-generated by cbindgen */

#ifndef AGENT_DB_CORE_H
#define AGENT_DB_CORE_H

/* Warning: This file is auto-generated. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef enum CAgentDbErrorCode {
  Success = 0,
  InvalidParam = -1,
  NotFound = -2,
  IoError = -3,
  MemoryError = -4,
  InternalError = -5,
  SerializationError = -6,
  NetworkError = -7,
  AuthenticationError = -8,
  PermissionDenied = -9,
} CAgentDbErrorCode;

typedef struct AgentStateDB AgentStateDB;

typedef struct CAgentStateDB {
  struct AgentStateDB *inner;
} CAgentStateDB;

struct CAgentStateDB *agent_db_create(const char *db_path);

void agent_db_destroy(struct CAgentStateDB *db);

enum CAgentDbErrorCode agent_db_save_state(struct CAgentStateDB *db,
                                           uint64_t agent_id,
                                           uint32_t state_type,
                                           const char *data,
                                           uintptr_t data_len);

enum CAgentDbErrorCode agent_db_load_state(struct CAgentStateDB *db,
                                           uint64_t _agent_id,
                                           char **out_data,
                                           uintptr_t *out_len);

enum CAgentDbErrorCode agent_db_vector_search(struct CAgentStateDB *db,
                                              const float *query_vector,
                                              uintptr_t _vector_len,
                                              uintptr_t _limit,
                                              uint64_t **out_results,
                                              uintptr_t *out_count);

void agent_db_free_memory(char *ptr);

void agent_db_free_results(uint64_t *results, uintptr_t count);

const char *agent_db_get_error_message(enum CAgentDbErrorCode error_code);

const char *agent_db_version(void);

enum CAgentDbErrorCode agent_db_init(void);

void agent_db_cleanup(void);

struct CAgentStateDB *agent_db_new(const char *db_path);

void agent_db_free(struct CAgentStateDB *db);

void agent_db_free_data(char *data);

#endif /* AGENT_DB_CORE_H */
