[package]
name = "multimodal-real-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-mem-intelligence = { path = "../../crates/agent-mem-intelligence" }
agent-mem-traits = { path = "../../crates/agent-mem-traits" }

# 核心依赖
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
