/* AgentDB Core C API */
/* Auto-generated by cbindgen */

#ifndef AGENT_DB_CORE_H
#define AGENT_DB_CORE_H

/* Warning: This file is auto-generated. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct CAgentStateDB {
  uint8_t _private[0];
} CAgentStateDB;

struct CAgentStateDB *agent_db_new(const char *db_path);

void agent_db_free(struct CAgentStateDB *db);

int agent_db_save_state(struct CAgentStateDB *db,
                        uint64_t agent_id,
                        uint64_t session_id,
                        int state_type,
                        const uint8_t *data,
                        uintptr_t data_len);

int agent_db_load_state(struct CAgentStateDB *db,
                        uint64_t agent_id,
                        uint8_t **data,
                        uintptr_t *data_len);

void agent_db_free_data(uint8_t *data, uintptr_t data_len);

const char *agent_db_get_last_error(struct CAgentStateDB *db);

#endif /* AGENT_DB_CORE_H */
