[package]
name = "intelligence-demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "intelligence-demo"
path = "src/main.rs"

[dependencies]
agent-mem-intelligence = { path = "../../crates/agent-mem-intelligence" }
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
