[package]
name = "simple-demo"
version = "0.1.0"
edition = "2021"
description = "Simple demonstration of AgentMem core functionality"

[dependencies]
# Core AgentMem dependencies
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
agent-mem-core = { path = "../../crates/agent-mem-core" }

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# UUID generation
uuid = { version = "1.0", features = ["v4"] }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Error handling
anyhow = "1.0"
