[package]
name = "agentmem-cli"
version = "6.0.0"
edition = "2021"
authors = ["AgentMem Team <support@agentmem.dev>"]
description = "Command-line interface for AgentMem - Enterprise-grade memory management for AI agents"
license = "MIT"
homepage = "https://agentmem.dev"
repository = "https://github.com/agentmem/agentmem"
keywords = ["ai", "memory", "agent", "cli", "tool"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "agentmem"
path = "src/main.rs"

[dependencies]
# Core dependencies
clap = { version = "4.4", features = ["derive", "env", "color"] }
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
thiserror = "1.0"

# HTTP client
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

# Terminal and UI
console = "0.15"
indicatif = "0.17"
dialoguer = "0.11"
tabled = "0.15"
colored = "2.1"

# File system and utilities
dirs = "5.0"
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
url = "2.5"

# Configuration
config = "0.14"
toml = "0.8"

# Logging
env_logger = "0.10"
log = "0.4"

# Template engine
handlebars = "4.5"

# Progress and async utilities
futures = "0.3"
stream-cancel = "0.8"

[dev-dependencies]
tempfile = "3.8"
assert_cmd = "2.0"
predicates = "3.0"

[features]
default = []
dev = ["env_logger/color"]
