[package]
name = "phase6-optimization-demo"
version = "2.0.0"
edition = "2021"

[dependencies]
agent-mem-core = { path = "../../crates/agent-mem-core" }
agent-mem-performance = { path = "../../crates/agent-mem-performance" }
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
anyhow = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
uuid = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tempfile = "3.0"
