[package]
name = "vector-store-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
agent-mem-storage = { path = "../../crates/agent-mem-storage" }
agent-mem-config = { path = "../../crates/agent-mem-config" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
anyhow = "1.0"

[[bin]]
name = "vector_store_demo"
path = "src/main.rs"
