[package]
name = "contextengine"
version = "0.1.0"
cjc-version = "1.0.0"
description = "ContextEngine - 仓颉版本的agentmem记忆功能实现"
authors = ["ContextEngine Team"]
license = "MIT"
output-type = "executable"

[source]
paths = ["src"]

[dependencies]