[package]
name = "real-implementation-demo"
version = "2.0.0"
edition = "2021"

[dependencies]
agent-mem-compat = { path = "../../crates/agent-mem-compat" }
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
agent-mem-llm = { path = "../../crates/agent-mem-llm" }
agent-mem-embeddings = { path = "../../crates/agent-mem-embeddings" }
agent-mem-storage = { path = "../../crates/agent-mem-storage" }
agent-mem-performance = { path = "../../crates/agent-mem-performance" }

tokio = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
