[package]
name = "phase4-demo"
version = "2.0.0"
edition = "2021"
description = "Phase 4 智能处理集成增强演示"

[dependencies]
# AgentMem dependencies
agent-mem-traits = { path = "../../crates/agent-mem-traits" }
agent-mem-core = { path = "../../crates/agent-mem-core" }
agent-mem-intelligence = { path = "../../crates/agent-mem-intelligence" }
agent-mem-llm = { path = "../../crates/agent-mem-llm" }

# Async runtime
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Time handling
chrono = { workspace = true }

# UUID generation
uuid = { workspace = true, features = ["v4"] }

# Futures
futures = "0.3"

[[bin]]
name = "intelligence_demo"
path = "src/main.rs"
